#!/usr/bin/env node
// One-shot setup for a fresh clone. Installs the server's dependencies and wires
// up the MCP config with ABSOLUTE paths resolved to *this* clone — which is what
// makes it portable, because Claude Code and omp ignore the `cwd` field and spawn
// from the project root, so a relative `src/index.ts` would not resolve.
//
// Usage:  node scripts/setup.mjs      (or: npm run setup)
//
// It:
//   1. runs `npm install` in server/
//   2. writes a project-local .mcp.json (works the moment you open this repo in
//      Claude Code) and gitignores it (paths are machine-specific)
//   3. prints the ready-to-paste snippet for global / omp / generic use
//
// Uses only Node built-ins, so it runs before anything is installed.

import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { existsSync, readFileSync, writeFileSync } from "node:fs";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const serverDir = join(root, "server");
const tsxBin = join(serverDir, "node_modules", ".bin", "tsx");
const entry = join(serverDir, "src", "index.ts");

const bold = (s) => `\x1b[1m${s}\x1b[0m`;
const green = (s) => `\x1b[32m${s}\x1b[0m`;
const dim = (s) => `\x1b[2m${s}\x1b[0m`;

console.log(bold("\n▸ tldraw-mcp setup\n"));

// 1. Install server dependencies
console.log("Installing server dependencies…");
execSync("npm install", { cwd: serverDir, stdio: "inherit" });
if (!existsSync(tsxBin)) {
  console.error(`\nExpected ${tsxBin} after install but it's missing. Aborting.`);
  process.exit(1);
}

// The MCP server entry. Absolute paths -> works no matter what cwd the client
// spawns us from. The daemon (canvas) is auto-started on first use; nothing else
// to run.
const serverEntry = {
  type: "stdio",
  command: tsxBin,
  args: [entry],
  env: {},
};

// 2. Write a project-local .mcp.json (merge, don't clobber other servers)
const mcpPath = join(root, ".mcp.json");
let mcp = { mcpServers: {} };
if (existsSync(mcpPath)) {
  try {
    mcp = JSON.parse(readFileSync(mcpPath, "utf8"));
    mcp.mcpServers ||= {};
  } catch {
    /* start fresh if unreadable */
  }
}
mcp.mcpServers.tldrawserver = serverEntry;
writeFileSync(mcpPath, JSON.stringify(mcp, null, 2) + "\n");
console.log(green(`\n✓ Wrote ${mcpPath}`));

// Keep the machine-specific config out of git.
const giPath = join(root, ".gitignore");
let gi = existsSync(giPath) ? readFileSync(giPath, "utf8") : "";
if (!gi.split(/\r?\n/).includes(".mcp.json")) {
  gi += (gi.endsWith("\n") || gi === "" ? "" : "\n") + "\n# machine-specific MCP config (generated by scripts/setup.mjs)\n.mcp.json\n";
  writeFileSync(giPath, gi);
  console.log(green("✓ Added .mcp.json to .gitignore"));
}

// 3. Print copy-paste guidance for other clients
const snippet = JSON.stringify({ tldrawserver: serverEntry }, null, 2)
  .split("\n")
  .map((l) => "    " + l)
  .join("\n");

console.log(`
${bold("Done.")} The tldraw planning board is set up for this clone.

${bold("Claude Code")} — already wired. Open this repo in Claude Code (or restart it)
and the ${green("tldrawserver")} MCP server is available. Nothing to start: the canvas
daemon auto-launches the first time an agent draws.

To use it from ${bold("any")} project (not just this repo), add this under
${dim('"mcpServers"')} in ${bold("~/.claude.json")}:
${snippet}

${bold("omp")} — add the same entry under "mcpServers" in ${bold("~/.omp/agent/mcp.json")},
then restart omp (it caches config at startup).

${bold("View the board")}: once an agent has drawn something, open ${green("http://localhost:3002")}.
The daemon shuts itself down ~1 min after the last agent disconnects.
`);
